baseURL = 'https://hamster2.top/'
languageCode = 'es-AR'
title = 'Hamster Kombat'
theme = "hamster"

[params]
description = "Hamster Kombat, 17/18 de Junio: Combo diario, cifrado diario, guía de airdrops, guía de inicio y mucho más."
netlify_deployment_status_badge = "https://api.netlify.com/api/v1/badges/47c5327b-3882-482f-81c0-c21705c2c2b8/deploy-status"
hideMadeWithLine = true
